name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
        packages: read
    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1.1.1
        with: 
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          create_credentials_file: true
          access_token_lifetime: '300s'
          cleanup_credentials: false


      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v1.1.1

      - name: teste
        run: |-
          echo ${{ secrets.WIF_PROVIDER}}
          echo ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: 'gcloud test'
        run: |-
          gcloud services list

      - name: Generate Zip file
        run: |
          mkdir terraform/cloud_function
          cd cloud_function
          zip source.zip main.py requirements.txt 
          mv source.zip ../terraform/cloud_function
          cd ..
          ls terraform/cloud_function

      - name: Change Directory
        run: cd terraform
        
      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        
        with:
          terraform_version: "1.6.5"

      # Step 3: Initialize Terraform
      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Refresh
        working-directory: ./terraform
        env:
            TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
            TF_VAR_region: 'us-central1'
            TF_VAR_service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
            TF_VAR_bucket_name: '${{ secrets.PROJECT_ID }}-classify-emails'
            TF_VAR_gcp_credentials_file: ${{ steps.auth.outputs.credentials_file }}
        run: terraform refresh

      # Step 4: Deploy Infrastructure using Terraform
      - name: Terraform plan
        working-directory: ./terraform
        env:
            TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
            TF_VAR_region: 'us-central1'
            TF_VAR_service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
            TF_VAR_bucket_name: '${{ secrets.PROJECT_ID }}-classify-emails'
            TF_VAR_gcp_credentials_file: ${{ steps.auth.outputs.credentials_file }}
        run: terraform plan

      - name: Deploy Infrastructure
        working-directory: ./terraform
        env:
            TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
            TF_VAR_region: 'us-central1'
            TF_VAR_service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
            TF_VAR_bucket_name: '${{ secrets.PROJECT_ID }}-classify-emails'
            TF_VAR_gcp_credentials_file: ${{ steps.auth.outputs.credentials_file }}

        run: terraform apply -auto-approve

      - name: Deploy Cloud Function
        working-directory: ./cloud_function
        env: 
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            GOOGLE_CLOUD_PROJECT: ${{ secrets.PROJECT_ID }}
        
        run: |
          gcloud functions deploy classify-emails \
          --gen2 \
          --region=us-central1 \
          --memory=512MB \
          --runtime=python310 \
          --trigger-http \
          --allow-unauthenticated \
          --source=. \
          --set-env-vars OPENAI_API_KEY=$OPENAI_API_KEY,PROJECT_ID=${{ secrets.PROJECT_ID }} \
          --service-account ${{ secrets.SERVICE_ACCOUNT_EMAIL }} \
          --entry-point main \
          --ingress-settings=all 